# -*- coding: utf-8 -*-
"""Dashboard_dataset6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gfy7joxvqXTh02Ml6hBeJV37DL-1yOk
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import pickle
import plotly.express as px
import plotly.graph_objects as go
from PIL import Image
import base64

# Konfigurasi halaman
st.set_page_config(
    page_title="Prediksi Kalori Makanan",
    page_icon="🍽️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 10px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
    }
    .metric-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 1rem;
        border-radius: 10px;
        color: white;
        text-align: center;
    }
    .result-box {
        background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
        padding: 2rem;
        border-radius: 10px;
        color: white;
        text-align: center;
        margin-top: 1rem;
    }
    .warning-box {
        background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        padding: 1rem;
        border-radius: 10px;
        color: white;
        text-align: center;
    }
    .info-box {
        background: #f0f2f6;
        padding: 1rem;
        border-radius: 10px;
        margin-top: 1rem;
    }
    h1, h2, h3 {
        color: #333;
    }
</style>
""", unsafe_allow_html=True)

# Load model
@st.cache_resource
def load_models():
    model = joblib.load('calorie_food_prediction_model_Gizi.pkl')
    scaler = pickle.load(open('scaler.pkl', 'rb'))
    return model, scaler

# Header
st.markdown("""
<div class="main-header">
    <h1>🍽️ Prediksi Kalori Makanan</h1>
    <p>Estimasi kalori makanan berdasarkan kandungan makronutrien dan mikronutrien</p>
</div>
""", unsafe_allow_html=True)

# Load models
try:
    model, scaler = load_models()
    st.success("✅ Model berhasil dimuat!")
except Exception as e:
    st.error(f"❌ Gagal memuat model: {e}")
    st.stop()

# Sidebar untuk input
with st.sidebar:
    st.markdown("## 📊 Input Data Makanan")
    st.markdown("Masukkan kandungan gizi makanan Anda:")

    st.markdown("### 🥩 Makronutrien")
    col1, col2 = st.columns(2)
    with col1:
        protein = st.number_input("Protein (g)", min_value=0.0, max_value=200.0, value=10.0, step=1.0)
        carbohydrate = st.number_input("Karbohidrat (g)", min_value=0.0, max_value=300.0, value=20.0, step=1.0)
        fat = st.number_input("Lemak (g)", min_value=0.0, max_value=150.0, value=5.0, step=1.0)
    with col2:
        sugar = st.number_input("Gula (g)", min_value=0.0, max_value=150.0, value=2.0, step=1.0)
        fiber = st.number_input("Serat (g)", min_value=0.0, max_value=50.0, value=3.0, step=1.0)

    st.markdown("### 🧂 Mikronutrien")
    sodium = st.number_input("Sodium (mg)", min_value=0.0, max_value=5000.0, value=100.0, step=50.0)

    st.markdown("### 👤 Informasi Tambahan")
    usia = st.slider("Usia (tahun)", min_value=10, max_value=80, value=30, step=1)

    # Informasi nilai gizi per gram
    st.markdown("---")
    st.markdown("### 📖 Nilai Gizi per Gram")
    st.info("""
    - 1g Protein = 4 kkal
    - 1g Karbohidrat = 4 kkal
    - 1g Lemak = 9 kkal
    """)

    # Tombol prediksi
    st.markdown("---")
    predict_button = st.button("🔮 Prediksi Kalori", use_container_width=True)

# Konten utama
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("""
    <div class="metric-card">
        <h3>🥩 Protein</h3>
        <h2>{:.1f} g</h2>
        <p>{:.0f} kkal</p>
    </div>
    """.format(protein, protein * 4), unsafe_allow_html=True)

with col2:
    st.markdown("""
    <div class="metric-card">
        <h3>🍚 Karbohidrat</h3>
        <h2>{:.1f} g</h2>
        <p>{:.0f} kkal</p>
    </div>
    """.format(carbohydrate, carbohydrate * 4), unsafe_allow_html=True)

with col3:
    st.markdown("""
    <div class="metric-card">
        <h3>🧈 Lemak</h3>
        <h2>{:.1f} g</h2>
        <p>{:.0f} kkal</p>
    </div>
    """.format(fat, fat * 9), unsafe_allow_html=True)

# Grafik ringkasan makronutrien
st.markdown("---")
st.markdown("### 📊 Komposisi Makronutrien")

# Data untuk chart
macro_data = pd.DataFrame({
    'Nutrisi': ['Protein', 'Karbohidrat', 'Lemak'],
    'Gram': [protein, carbohydrate, fat],
    'Kalori': [protein * 4, carbohydrate * 4, fat * 9]
})

col1, col2 = st.columns(2)

with col1:
    fig1 = px.bar(macro_data, x='Nutrisi', y='Gram',
                  color='Nutrisi', title="Komposisi Makronutrien (gram)",
                  color_discrete_sequence=['#667eea', '#764ba2', '#f093fb'])
    fig1.update_layout(showlegend=False, height=400)
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    fig2 = px.pie(macro_data, values='Kalori', names='Nutrisi',
                  title="Kontribusi Kalori", hole=0.3,
                  color_discrete_sequence=['#667eea', '#764ba2', '#f093fb'])
    fig2.update_layout(height=400)
    st.plotly_chart(fig2, use_container_width=True)

# Prediksi
if predict_button:
    with st.spinner("Menghitung prediksi kalori..."):
        # Buat dataframe untuk prediksi
        input_data = pd.DataFrame([[
            protein, carbohydrate, fat, sugar, sodium, fiber, usia,
            protein * fat,  # protein_fat_interaction
            carbohydrate * sugar  # carb_sugar_interaction
        ]], columns=[
            'protein_g', 'carbohydrate_g', 'fat_g', 'sugar_g',
            'sodium_mg', 'fiber_g', 'usia',
            'protein_fat_interaction', 'carb_sugar_interaction'
        ])

        # Scaling dan prediksi
        input_scaled = scaler.transform(input_data)
        prediction = model.predict(input_scaled)[0]

        # Hitung kalori dari rumus dasar
        kalori_manual = (protein * 4) + (carbohydrate * 4) + (fat * 9)

        # Tampilkan hasil
        st.markdown("---")
        col1, col2, col3 = st.columns([1, 2, 1])

        with col2:
            st.markdown(f"""
            <div class="result-box">
                <h3>✨ Hasil Prediksi ✨</h3>
                <h1 style="font-size: 4rem;">{prediction:.0f}</h1>
                <h2>kkal per sajian</h2>
                <hr>
                <p>📊 Kalori berdasarkan rumus: {kalori_manual:.0f} kkal</p>
                <p>🤖 Kalori prediksi ML: {prediction:.0f} kkal</p>
            </div>
            """, unsafe_allow_html=True)

        # Rekomendasi berdasarkan kalori
        st.markdown("---")
        st.markdown("### 💡 Rekomendasi")

        if prediction < 100:
            st.info("🍃 **Makanan rendah kalori** - Cocok untuk camilan atau diet.")
        elif prediction < 300:
            st.success("✅ **Makanan kalori sedang** - Pilihan yang baik untuk makanan utama.")
        elif prediction < 500:
            st.warning("⚠️ **Makanan kalori tinggi** - Konsumsi dengan bijak.")
        else:
            st.error("🔥 **Makanan sangat tinggi kalori** - Pertimbangkan porsi lebih kecil.")

        # Tabel perbandingan
        st.markdown("---")
        st.markdown("### 📋 Detail Prediksi")

        comparison_data = {
            'Metode': ['Rumus Standar (4-4-9)', 'Prediksi Machine Learning'],
            'Kalori (kkal)': [f"{kalori_manual:.0f}", f"{prediction:.0f}"],
            'Selisih': [f"0", f"{abs(prediction - kalori_manual):.0f}"]
        }
        df_compare = pd.DataFrame(comparison_data)
        st.table(df_compare)

# Footer
st.markdown("---")
st.markdown("""
<div class="info-box">
    <p align="center">
        <b>📌 Tentang Aplikasi</b><br>
        Aplikasi ini menggunakan model Machine Learning (XGBoost) untuk memprediksi kalori makanan
        berdasarkan kandungan protein, karbohidrat, lemak, gula, sodium, serat, dan usia.
        Model telah dilatih dengan data nilai gizi dan memiliki akurasi tinggi (R² = 0.95).
    </p>
</div>
""", unsafe_allow_html=True)

# Informasi model di sidebar
with st.sidebar:
    st.markdown("---")
    st.markdown("### 🤖 Informasi Model")
    st.info("""
    **Model**: XGBoost Regressor (Tuned)

    **Metrik Performa**:
    - MAE: 20.31 kkal
    - RMSE: 39.70 kkal
    - R²: 0.95

    **Fitur Utama**:
    1. Lemak (fat_g)
    2. Karbohidrat (carbohydrate_g)
    3. Interaksi Protein-Lemak
    4. Gula (sugar_g)
    5. Interaksi Karbohidrat-Gula
    """)

    st.markdown("---")
    st.markdown("### 📞 Kontak")
    st.caption("Dibangun dengan Streamlit • Data Science Project")

# Catatan untuk deployment
st.markdown("""
---
<small>
🔬 Aplikasi ini untuk tujuan edukasi. Konsultasikan dengan ahli gizi untuk perencanaan diet yang akurat.
</small>
""", unsafe_allow_html=True)